---

- name: create group
  group: name={{ git_application_group }}
  sudo: yes

- name: create user
  user: name={{ git_application_user }} group={{ git_application_group }}
  sudo: yes

- name: create application directory (owned by ansible ssh user)
  file: path={{ git_application_deploy_to }} state=directory owner={{ git_application_user }} group={{ git_application_user }}
  sudo: yes

- name: install git
  sudo: yes
  apt: pkg=git update_cache=yes

- name: clone repo to application directory
  git: dest={{ git_application_deploy_to }} repo={{ git_application_repo }} version={{ git_application_version }} accept_hostkey=yes
  sudo: yes
  sudo_user: "{{ git_application_user }}"
  when: git_application_pull_from_git == True

- name: make application directory be owned by application user
  file: path={{ git_application_deploy_to }} state=directory recurse=yes owner={{ git_application_user }}
  sudo: yes
